src/main/java/edu/finalyear/project/models/Guardian.java
package edu.finalyear.project.models;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.codehaus.jackson.annotate.JsonBackReference;

@Entity
@Table(name = "guardian")
public class Guardian extends Account{

	@Column(name = "relation")
	private String relation;

	@Column(name = "occupation")
	private String occupation;

	@OneToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER, orphanRemoval = true)
	@JoinColumn(name = "student_id")
	private Student student;
	
	@Column(name = "student_id", insertable=false, updatable= false)
	private String studentId;
	
	@Transient
	@JsonBackReference
	private List<String> subjectsIds = new ArrayList<String>();

	public Guardian() {

	}

	public Guardian(String guardianId,String firstName, String relation) {
		super();
		this.firstName = firstName;
		this.relation = relation;
		this.id = guardianId;
		
	}

	
	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getRelation() {
		return relation;
	}

	public void setRelation(String relation) {
		this.relation = relation;
	}

	public String getOccupation() {
		return occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}
	
	
		
	public String getStudentId() {
		return studentId;
	}

	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}

	public Student getStudent() {
		return student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@Override
	public String toString() {
		return "StudentGuardian [guardianId="+id+"firstName=" + firstName + ", lastName="
				+ lastName + ", relation=" + relation + ", occupation="
				+ occupation + ", email=" + email + ", mobile=" + mobile
				+ ", address=" + address + "]";
	}

	@Override
	@Transient
	public List<String> getSubjectsIds() {
		// TODO Auto-generated method stub
		return this.subjectsIds;
	}

	@Override
	@Transient
	public void setSubjectsIds(List<String> subjectsIds) {
		// TODO Auto-generated method stub
		this.subjectsIds = subjectsIds;
	}

	@Override
	public String getClassId() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public String getGuardianStudentId() {
		// TODO Auto-generated method stub
		return this.studentId;
	}

	@Override
	public List<String> getClassIds() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setClassIds(List<String> classIds) {
		// TODO Auto-generated method stub
		
	}

}

src/main/java/edu/finalyear/project/controllers/CheckController.java
package edu.finalyear.project.controllers;

import java.io.IOException ;

import javax.servlet.http.HttpServletRequest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartFile;

import edu.finalyear.project.models.Account;
import edu.finalyear.project.models.Guardian;
import edu.finalyear.project.models.School;
import edu.finalyear.project.schoolprofile.SchoolProfile;
import edu.finalyear.project.models.Teacher;
import edu.finalyear.project.models.Student;
import edu.finalyear.project.models.TestAccount;
import edu.finalyear.project.models.TestTeacherAccount;
import edu.finalyear.project.service.AccountService;
//import edu.finalyear.project.service.SchoolProfileService;
import edu.finalyear.project.service.SchoolService;
//import edu.finalyear.project.service.TestAccountService;

@Controller
@RequestMapping(value = "cheking")
public class CheckController {

	@Autowired
	@Qualifier("SchoolService")
	private SchoolService schoolService;

	@Autowired
	@Qualifier("AccountService")
	private AccountService accountService;

//	@Autowired
//	@Qualifier("SchoolProfileService")
//	private SchoolProfileService spService;

	@RequestMapping(value = "view-subject")
	public String viewClass(Model model) {
		System.out.println("inside cheking/view-class");
		return "view-subject";
	}

	@RequestMapping(value = "addTeacher")
	public void addTeacher(Model model) {

		// schoolService.saveOrUpdateSchool(new School("APS",
		// "Army Public School"));
		System.out.println("School=>");
		School school = schoolService.getSchool("APS");
		System.out.println("School=>" + school);
		System.out
				.println("Teacher list of school id 1" + school.getTeachers());
		school.getTeachers().add(
				new Teacher("TeacherId_test", "firstName", "lastName","qualification"));
		schoolService.saveOrUpdateSchool(school);
	}

	@RequestMapping(value = "addStudent")
	public void addStudent() {
		System.out.println("==>Student befor persistant");
		School school = schoolService.getSchool("APS");
		System.out.println("==>Student after persistant = " + school);
		for (int i = 1; i < 30; i++) {
			Student student = new Student("StudentId" + Math.random(),
					"firstName", "schoolId");

			System.out.println("==>Student after persistant = " + student);
			school.getStudents().add(student);
		}
		schoolService.saveOrUpdateSchool(school);
	}

	@RequestMapping(value = "myprofile")
	public String test1(Model model) {
		System.out.println("inside test/tes1");
		return "profile-templet";
	}

	@RequestMapping(value = "test2")
	public String test2(Model model) {
		System.out.println("inside test/tes2");
		return "test/test2";
	}

	@RequestMapping(value = "profile")
	public String pro(Model model) {
		System.out.println("inside test/pro");
		return "profile";
	}

	@RequestMapping(value = "testimage")
	public String testimage(Model model) {
		// System.out.println("inside test/pro");
		System.out.println("inside testimage");
		return "test-page";
	}

	@RequestMapping(value = "loadimage", method = RequestMethod.GET)
	public String loadimage(Model model) {
		// System.out.println("inside test/pro");
		System.out.println("inside loadimage");
		return null;// "test-page";
	}

	@RequestMapping(value = "newschool")
	public String newSchool(Model model) {
		model.addAttribute("newSchoolProfile", new SchoolProfile());
		return "school-registration";
	}



	// /////////////////////////cheking augment////////\
	@RequestMapping(value = "aug")
	public String getPage() {
		return "new-activity";
	}

	@RequestMapping(value = "{id}")
	public void getAccount(@PathVariable String id) {
		System.out.println("Account"+accountService.getAccount(id));
	}



	@RequestMapping(value = "test-account")
	public void testAccount(){
//Random ran=new Random int arra[] = {12,23,45,34,453,4345,345,23,23,534,523,35,23,23,45,42,35,23,35,234,35,35,35,35};
		accountService.saveOrUpdateTeacher(new Teacher("teacher_test"+1, "firstName", "password", "qualificition"));//Account will insert too
		accountService.saveOrUpdateStudent(new Student("student_test"+1, "firstName", "APS","aps_class"));
//		accountService.saveOrUpdate(new Account("account_test", "firstName", "password"));//Only Account will insert
		
	}
}

src/main/java/edu/finalyear/project/controllers/ClassController.java
package edu.finalyear.project.controllers;

import static edu.finalyear.project.security.SecurityUtils.*;

import java.util.Collection;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.Set;

import org.hibernate.Hibernate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import edu.finalyear.project.models.Account;
import edu.finalyear.project.models.Comment;
import edu.finalyear.project.models.CompositeResult;
import edu.finalyear.project.models.MCQS;
import edu.finalyear.project.models.Post;
import edu.finalyear.project.models.SchoolClass;
import edu.finalyear.project.models.Student;
import edu.finalyear.project.models.Subject;
import edu.finalyear.project.models.Test;
import edu.finalyear.project.models.TestRecord;
import edu.finalyear.project.security.Role;
import edu.finalyear.project.security.SecurityUtils;
import edu.finalyear.project.service.AccountService;
import edu.finalyear.project.service.ClassAndSubjectService;
//import edu.finalyear.project.service.SchoolClassService;
import edu.finalyear.project.utils.ContextUtils;

@Controller
@PreAuthorize("hasAnyRole('ROLE_STUDENT')")
@RequestMapping(value = "/{schoolId}/my-class")
public class ClassController {

	@Autowired
	@Qualifier("ClassAndSubjectService")
	private ClassAndSubjectService csService;

	@Autowired
	@Qualifier("AccountService")
	private AccountService accountService;

	@Autowired
	@Qualifier("ContextSetting")
	private ContextUtils context;

	// return all subjects for /schoolid/my-class
	@RequestMapping(value = "")
	@PreAuthorize("hasAnyRole('ROLE_STUDENT')")
	public String getClassPage(Model model) {

		SchoolClass myClass = csService.getSchoolClass(getLogedInAccount()
				.getClassId(),true,true);
		Set<Student> students = myClass.getStudents();
		Set<Subject> subjects = myClass.getSubjects();

		model.addAttribute("subjects", subjects);
		model.addAttribute("students", students);
		model.addAttribute("schoolClass", myClass);
		System.out.println("ClassController: /{} Students=" + students);
		System.out.println("ClassController: /{} Teacher="
				+ subjects.iterator().next().getTeacher());

		return "classPage";
	}

	@RequestMapping(value = "/all-subjects")
	@PreAuthorize("hasAnyRole('ROLE_STUDENT')")
	public String getAllSubject(Model model) {
		System.out.println("ClassController:/getAllSubject");

		SchoolClass myClass = csService.getSchoolClass(getLogedInAccount()
				.getClassId(),false,true);
		Set<Student> students = myClass.getStudents();
		Set<Subject> subjects = myClass.getSubjects();

		model.addAttribute("subjects", subjects);
		model.addAttribute("schoolClass", myClass);
		System.out.println("ClassController:/getAllSubject");
		return "classPage";

	}

	@PreAuthorize("hasAnyRole('ROLE_STUDENT')")
	@RequestMapping(value = "/class-mates")
	public String getClassMates(Model model) {
		System.out.println("ClassController:/getClassMates");

		SchoolClass myClass = csService.getSchoolClass(getLogedInAccount()
				.getClassId(),true,false);

		Set<Student> students = myClass.getStudents();

		model.addAttribute("students", students);
		model.addAttribute("schoolClass", myClass);

		System.out.println("ClassController:/getAllSubject");
		return "classPage";

	}

	@PreAuthorize("hasAnyRole('ROLE_STUDENT')")
	@RequestMapping(value = "/{subjectId}", method = RequestMethod.GET)
	public String getSubject(Model model,
			@PathVariable("subjectId") String subjectId) {

		System.out.println("ClassController:/getSubject=> subjectId="
				+ subjectId);
		Test test = null;
		try {
			test = csService.getEnableTest(true, subjectId);
		} catch (Exception exception) {
			System.out.println("???Exception getEnabledTest");
		}

		String viewName = "subjectPage";

		System.out.println("ClassController:/getSubject=> test = " + test);

		if (test != null) {
			System.out.println("ClassController:/getSubject=> test!=null");
			TestRecord testRecord = csService.getTestRecordOnTestId(
					SecurityUtils.getLogedInAccount().getId(),
					test.getDateId(), test.getId());

			if (testRecord != null) { // if record is available
				// if (test.getId() == testRecord.getTestId()) {
				System.out
						.println("ClassController:/getSubject=> testRecord!=null");
				Subject subject = csService.getSubject(subjectId, true, false);
				Collections.reverse(subject.getPosts());
				viewName = "subjectPage";
				model.addAttribute("newPost", new Post());
				model.addAttribute("newComment", new Comment());
				model.addAttribute("subject", subject);

			} else {
				System.out
						.println("ClassController:/getSubject=> test level_2");
				for (int i = 0; i < test.getMcqs().size(); i++)
					test.getMcqs().get(i).setRightAnswer("");

				model.addAttribute("test", test);
				model.addAttribute("subject",
						csService.getSubject(subjectId, false, false));
				viewName = "createTest";
			}
		} else {
			System.out.println("ClassController:/getSubject=> test==null");
			viewName = "subjectPage";
			Subject subject = csService.getSubject(subjectId, true, false);
			Collections.reverse(subject.getPosts());
			model.addAttribute("newPost", new Post());
			model.addAttribute("newComment", new Comment());
			model.addAttribute("subject", subject);
		}
		return viewName;
	}

	@PreAuthorize("hasAnyRole('ROLE_STUDENT')")
	@RequestMapping(value = "/{subjectId}/chek-test", method = RequestMethod.POST)
	public String checkTest(Model model,
			@PathVariable("subjectId") String subjectId,
			@ModelAttribute("test") Test test) {
		int right = 0;
		int wrong = 0;

		Test test2 = csService.getTest(test.getId());
		int total = test2.getMcqs().size();

		for (int i = 0; i < test.getMcqs().size(); i++) {
			try {
				if (test.getMcqs()
						.get(i)
						.getRightAnswer()
						.equalsIgnoreCase(
								test2.getMcqs().get(i).getRightAnswer())) {
					right++;
					System.out.println("ClassController=>checkTest/ right = "
							+ right);
				} else {
					wrong++;
					System.out.println("ClassController=>checkTest/ wrong = "
							+ wrong);
				}
			} catch (NullPointerException e) {
				wrong++;
				System.out.println("Null pointer Ex in right option wrong ="
						+ wrong);
			}

		}

		TestRecord testRecord = new TestRecord(test2.getnPQ(), right, wrong,
				total, test2.getId(),
				SecurityUtils.getLogedInAccount().getId(), subjectId,
				test2.getTestName(), test2.getDateId());

		System.out.println("ClassController=>checkTest/ TestRecord = "
				+ testRecord);
		csService.saveOrUpdateTestRecord(testRecord);
		CompositeResult compResult = csService.getCompositeResult(subjectId,
				SecurityUtils.getLogedInAccount().getId());
		if (compResult != null) {
			double tempPer = (testRecord.getPercent()+compResult.getComPercent())/(compResult.getNumOfTest()+1);
			 compResult.setComPercent(tempPer);
			compResult.setNumOfTest(compResult.getNumOfTest() + 1);

		} else {
			compResult = new CompositeResult(subjectId, SecurityUtils
					.getLogedInAccount().getId(), 1, testRecord.getPercent());
		}
		csService.saveOrUpdateCompositeResult(compResult);
		model.addAttribute("testRecord", testRecord);
		return "testResult";

	}

	@PreAuthorize("hasAnyRole('ROLE_STUDENT')")
	@RequestMapping(value = "/{subjectId}/view-result-history", method = RequestMethod.GET)
	public String viewStudentResult(Model model,
			@PathVariable("subjectId") String subjectId) {
		System.out.println("SubjectController: /viewStudentResult ");

		String id = SecurityUtils.getLogedInAccount().getId();
		if(SecurityUtils.hasRoleOrPermission("ROLE_GUARDIAN")){
			
		}else{
			
		}
		
		
		List<TestRecord> records = csService.getTestRecordsOnStuAndSubId(
				subjectId, id);
		CompositeResult compResult = csService.getCompositeResult(subjectId, id);
		
		for (TestRecord x : records)
			System.out.println("ClassController/viewResultHistory record = "
					+ x);
		
		System.out.println("ClassController/viewResultHistory compRecord = "+ compResult);
	
		model.addAttribute("compResult",compResult);
		model.addAttribute("testRecords", records);

		return "testResult";
	}

}

src/main/webapp/WEB-INF/views/augment/all-test.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="security"
	uri="http://www.springframework.org/security/tags"%>

<%@ include file="/WEB-INF/views/augment/jsp-f/contextSetting.jspf"%>
<%@ include file="/WEB-INF/views/augment/jsp-f/urls.jspf"%>

<!DOCTYPE HTML>
<html>
<head>
<title>${context_school.fullName}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords"
	content="Augment Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />

<!-- //lined-icons -->
<%@ include file="/WEB-INF/views/augment/jsp-f/design-css.jspf"%>
<%@ include file="/WEB-INF/views/augment/jsp-f/head-script.jspf"%>
<!--clock init-->
</head>
<body>
	<div class="page-container">
		<!--/content-inner-->
		<div class="left-content">
			<div class="inner-content">
				<!-- header-starts -->

				<%@ include file="/WEB-INF/views/augment/jsp-f/header.jspf"%>

				<!-- //header-ends -->
				<!--//outer-wp-->
				<div class="outter-wp">
					<!--sub-heard-part-->
					<div class="sub-heard-part">
						<ol class="breadcrumb m-b-0">
							<li><a href="index.html">Home</a></li>
							<li class="active">Blank Page</li>
						</ol>
					</div>
					<!--//sub-heard-part-->
					<div class="graph-visual tables-main">
						<h2 class="inner-tittle">Blank Page</h2>
						<div class="graph">
<%-- 							<c:forEach items="${subject.test}" var="test"> --%>
								<h1>
									<a href="${mySubject}/${subject.subjectId}/all-test?testId=${subject.test.id}">Test Name: ${subject.test.testName }</a>
									
								</h1>
<%-- 							</c:forEach> --%>


						</div>

					</div>
					<!--//graph-visual-->
				</div>
				<!--//outer-wp-->
				<!--footer section start-->
				<%@ include file="/WEB-INF/views/augment/jsp-f/footer.jspf"%>
				<!--footer section end-->
			</div>
		</div>
		<!--//content-inner-->
		<!--/sidebar-menu-->
		<%@ include file="/WEB-INF/views/augment/jsp-f/sidebar.jspf"%>
	</div>
	<%@ include file="/WEB-INF/views/augment/jsp-f/body-script.jspf"%>
</body>
</html>

src/main/webapp/WEB-INF/views/augment/classPage.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix = "fn" uri = "http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="security"
	uri="http://www.springframework.org/security/tags"%>

<%@ include file="/WEB-INF/views/augment/jsp-f/contextSetting.jspf"%>
<%@ include file="/WEB-INF/views/augment/jsp-f/urls.jspf"%>

<!DOCTYPE HTML>
<html>
<head>
<title>${context_school.fullName}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords"
	content="Augment Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />

<!-- //lined-icons -->
<%@ include file="/WEB-INF/views/augment/jsp-f/design-css.jspf"%>
<%@ include file="/WEB-INF/views/augment/jsp-f/head-script.jspf"%>
<!--clock init-->
</head>
<body>
	<div class="page-container">
		<!--/content-inner-->
		<div class="left-content">
			<div class="inner-content">
				<!-- header-starts -->

				<%@ include file="/WEB-INF/views/augment/jsp-f/header.jspf"%>

				<!-- //header-ends -->
				<!--//outer-wp-->
				<div class="outter-wp">
					<!--sub-heard-part-->
					<div class="sub-heard-part">
						<ol class="breadcrumb m-b-0">
							<li><a href="index.html">Home</a></li>
							<li class="active">Blank Page</li>

						</ol>
					</div>


					<!--//sub-heard-part-->
					<div class="graph-visual tables-main">
						<h2 class="inner-tittle">${fn:split(schoolClass.classId,'@')[0]}</h2>
						<c:if test="${not empty subjects }">
							<%@ include file="/WEB-INF/views/augment/jsp-f/subjectsList.jspf"%>
						</c:if>


						<br>

						<div class="graph">
							<div class="block-page">

						<%
							for (int i = 0; i < 6; i++) { // it will repeat al students i<times
						%>
						<c:if test="${not empty students }">
							<%@ include file="/WEB-INF/views/augment/jsp-f/studentsList.jspf"%>
						</c:if>
						<%
							}
						%>

					</div>
				</div>

			</div>
			<!--//graph-visual-->

		</div>
		<!--//outer-wp-->

		<!--footer section start-->
		<%@ include file="/WEB-INF/views/augment/jsp-f/footer.jspf"%>
		<!--footer section end-->




		<!--//content-inner-->
		<!--/sidebar-menu-->
		<%@ include file="/WEB-INF/views/augment/jsp-f/sidebar.jspf"%>
	</div>
	<%@ include file="/WEB-INF/views/augment/jsp-f/body-script.jspf"%>
</body>
</html>

src/main/webapp/WEB-INF/views/augment/createTest.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="security"
	uri="http://www.springframework.org/security/tags"%>


<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ include file="/WEB-INF/views/augment/jsp-f/contextSetting.jspf"%>
<%@ include file="/WEB-INF/views/augment/jsp-f/urls.jspf"%>

<!DOCTYPE HTML>
<html>
<head>
<title>${context_school.fullName}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords"
	content="Augment Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />

<!-- //lined-icons -->
<%@ include file="/WEB-INF/views/augment/jsp-f/design-css.jspf"%>
<%@ include file="/WEB-INF/views/augment/jsp-f/head-script.jspf"%>
<!-- <script type="text/javascript" -->
<%-- 	src="<c:url value='/resources/iownschool/js/jquery-1.10.2.min.js'/>"></script> --%>

<!--clock init-->
</head>
<body>
	<div class="page-container">
		<!--/content-inner-->
		<div class="left-content">
			<div class="inner-content">
				<!-- header-starts -->

				<%@ include file="/WEB-INF/views/augment/jsp-f/header.jspf"%>

				<!-- //header-ends -->
				<!--//outer-wp-->
				<div class="outter-wp">
					<!--sub-heard-part-->
					<div class="sub-heard-part">
						<ol class="breadcrumb m-b-0">
							<li><a href="index.html">Home</a></li>
							<li class="active">Blank Page</li>
						</ol>
					</div>
					<!--//sub-heard-part-->




					<security:authorize access="hasRole('ROLE_TEACHER')">

						<%@ include file="/WEB-INF/views/augment/jsp-f/teacherTest.jspf"%>
						<%
							System.out.println("inside createTest RoleTeacher");
						%>
					</security:authorize>

					<security:authorize access="hasRole('ROLE_STUDENT')">
						<%@ include file="/WEB-INF/views/augment/jsp-f/studentTest.jspf"%>
						<%
							System.out.println("inside createTest RoleStudent");
						%>
					</security:authorize>
				</div>
				<!--//graph-visual-->
			</div>
			<!--//outer-wp-->
			<!--footer section start-->
			<%@ include file="/WEB-INF/views/augment/jsp-f/footer.jspf"%>
			<!--footer section end-->
		</div>
	</div>
	<!--//content-inner-->
	<!--/sidebar-menu-->
	<%@ include file="/WEB-INF/views/augment/jsp-f/sidebar.jspf"%>
	</div>
	<%@ include file="/WEB-INF/views/augment/jsp-f/body-script.jspf"%>
</body>
</html>

src/main/webapp/WEB-INF/views/augment/test.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>

<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>${context_school.fullName}</title>
</head>
<body>


	<form:form modelAttribute="schoolPro.about"
		action="/project/tester/posttest">
		<form:input path="topic" /><br>
		<c:forEach items="${ about.aboutItem}" var="item" varStatus="loop">

			<form:input path="aboutItem[${loop.index }].heading" />
			<form:input path="aboutItem[${loop.index }].subHeading" />

		</c:forEach>
		<input type="submit" />
	</form:form>

</body>
</html>